### ISSUE TITLE
Disallowed attribute in HTML tag 'meta name= and content='

### ISSUE THREAD

**Issue by orballo** [frontity/saturn-theme#116]
The `content` attribute in `meta` tag is being parsed wrongly.

`<meta data-react-helmet="true" property="og:description" content="&quot;Zach Collins, &quot;power" forward" oriundo de Las Vegas, es uno de los prospectos con mayor potencial de la camada."="null"/>`

Links:
- [x] https://amp.wp-pwa.com/zach-collins/?siteId=j9ms2Rr6EqBhcajot&env=prod&dev=false&singleType=post&singleId=1559&initialUrl=https://thewing.es/zach-collins/
- [x] https://amp.wp-pwa.com/david-fizdale-aterriza-nueva-york-aportar-knicks/?siteId=j9ms2Rr6EqBhcajot&env=prod&dev=false&singleType=post&singleId=12513&initialUrl=https://thewing.es/david-fizdale-aterriza-nueva-york-aportar-knicks/
- [x] https://amp.wp-pwa.com/zach-collins/?siteId=j9ms2Rr6EqBhcajot&env=prod&dev=false&singleType=post&singleId=1559&initialUrl=https://thewing.es/zach-collins/
- [x] https://amp.wp-pwa.com/nba-draft-bold-predictions/?siteId=j9ms2Rr6EqBhcajot&env=prod&dev=false&singleType=post&singleId=1836&initialUrl=https://thewing.es/nba-draft-bold-predictions/
- [x] https://amp.wp-pwa.com/warriors-encantados-villanos-nba/?siteId=j9ms2Rr6EqBhcajot&env=prod&dev=false&singleType=post&singleId=5265&initialUrl=https://thewing.es/warriors-encantados-villanos-nba/
- [x] https://amp.wp-pwa.com/zaza-pachulia-lesionar-russell-westbrook/?siteId=j9ms2Rr6EqBhcajot&env=prod&dev=false&singleType=post&singleId=9697&initialUrl=https://thewing.es/zaza-pachulia-lesionar-russell-westbrook/
- [x] https://amp.wp-pwa.com/ricky-rubio-metamorfosis-utah-jazz/?siteId=j9ms2Rr6EqBhcajot&env=prod&dev=false&singleType=post&singleId=12083&initialUrl=https://thewing.es/ricky-rubio-metamorfosis-utah-jazz/
